name: Check unused imports using Pylint
on:
  pull_request:
    branches:
      - circinus
    paths:
      - '**'
      # - '!.github/**'
      - '!**/*.md'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  check-unused-imports:
    uses: vyos/.github/.github/workflows/check-unused-imports.yml@T6789-unused-import-fix
    secrets: inherit
